<a href="https://colab.research.google.com/github/ShrutiThakur3/VCET-DS/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 **Numpy**

In [ ]:
#In this example, we are creating a two-dimensional array that has the rank of 2 as it has 2 axes.
#The first axis(dimension) is of length 2, i.e., the number of rows, and the second axis(dimension) is of length 3,
#i.e., the number of columns. The overall shape of the array can be represented as (2, 3)
# Creating array object

import numpy as np
arr=np.array([[1,2,3],[4,2,5]] )
print("Array is of type:", type(arr))
print("No of dimension:",arr.ndim)
print("Shpe of the aarray:", arr.shape)
print("size of array:", arr.size)
print("data type:", arr.dtype)

Array is of type: <class 'numpy.ndarray'>
No of dimension: 2
Shpe of the aarray: (2, 3)
size of array: 6
data type: int64


In [ ]:
import numpy as np
arr=np.array([1,2,3])
print("Array with Rank 1:\n",arr)
arr=np.array([[1,2,3],[4,5,6]] )
print("array with rank 2:\n",arr)
arr=np.array((1,3,2))
print("\n Array created using""passed tuple:\n", arr)

Array with Rank 1:
 [1 2 3]
array with rank 2:
 [[1 2 3]
 [4 5 6]]

 Array created usingpassed tuple:
 [1 3 2]


In [ ]:
import numpy as np

# creating array
arr = np.array([2, 4, 6, 8, 10])

# creating copy of array
c = arr.copy()

# both arr and c have different id
print("id of arr", id(arr))
print("id of c", id(c))

# changing original array
# this will not effect copy
arr[0] = 12

# printing array and copy
print("original array- ", arr)
print("copy- ", c)

id of arr 138218491005904
id of c 138218491008496
original array-  [12  4  6  8 10]
copy-  [ 2  4  6  8 10]


In [ ]:
# Let's define our function
# Parameters: Input Array
def sum(array):

	# Set variable for our final answer
	sum = 0

	# Parse through our array
	for i in array:
		# Continuously add current element
		# to final sum
		sum += i
	# Return our sum
	return sum
# Create a test array
testArray = [1, 3, 34, 92, 29, 48, 20.3]

# Test our function
print('The sum of your numbers is ' + str(sum(testArray)))

The sum of your numbers is 227.3


In [ ]:
# Create a sequence of integers from 10 to 1 with a step of -2

import numpy as np
a=np.arange(10,1,-2)
print(" a sequential array with a negative step:\n",a)

# Indexes are specified inside the np.array method.
newarr=a[np.array([3,1,2])]
print("\n Elements at these indices are:\n",newarr)


 a sequential array with a negative step:
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]


In [ ]:
#The result includes the start index, but excludes the end index
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [ ]:
#The copy SHOULD NOT be affected by the changes made to the original array.
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
#The view SHOULD be affected by the changes made to the original array.
import numpy as np
arr=np.array([1,2,3,4,2,5] )
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  2  5]
[42  2  3  4  2  5]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)


(2, 4)


In [ ]:
# Create an array with 5 dimensions using ndmin
#using a vector with values 1,2,3,4 and verify that last dimension has value 4:
import numpy as np
arr=np.array([1,2,3,4], ndmin=5)
print(arr)
print('Shape of array:',arr.shape)

[[[[[1 2 3 4]]]]]
Shape of array: (1, 1, 1, 1, 4)


In [ ]:
#Convert the following 1-D array with 12 elements into a 2-D array.

#The outermost dimension will have 4 arrays, each with 3 elements:

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# Python code to demonstrate matrix operations
# add(), subtract() and divide()

# importing numpy for matrix operations
import numpy

# initializing matrices
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])

# using add() to add matrices
print ("The element wise addition of matrix is : ")
print (numpy.add(x,y))

# using subtract() to subtract matrices
print ("The element wise subtraction of matrix is : ")
print (numpy.subtract(x,y))

# using divide() to divide matrices
print ("The element wise division of matrix is : ")
print (numpy.divide(x,y))


The element wise addition of matrix is : 
[[ 8 10]
 [13 15]]
The element wise subtraction of matrix is : 
[[-6 -6]
 [-5 -5]]
The element wise division of matrix is : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]
